/// <reference types="vite/client" />
/// <reference types="vite-plugin-svgr/client" />

interface ImportMetaEnv {
  readonly VITE_RESEND_API_KEY: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}

// Cloudflare secrets are not auto-generated by `wrangler types`.
// Manually augment Cloudflare.Env here so JWT_SECRET is type-safe
// without modifying the auto-generated worker-configuration.d.ts.
declare namespace Cloudflare {
  interface Env {
    JWT_SECRET: string;
  }
}
